version: "3.8"
services:
  postgres-tc:
    container_name: postgres-sql-tickets
    image: postgres:16
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - tickets
    restart: unless-stopped

  app:
    image: openjdk:21
    container_name: tickets-api
    build:
      context: .
    networks:
      - tickets
    ports:
      - "8080:8080"
    depends_on:
      - postgres-tc
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ "sh", "-c", "java -jar build/libs/tickets-api-1.0.0.jar" ]

  pgadmin:
    container_name: pgadmin-tickets
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: louail.enzo@orange.fr
      PGADMIN_DEFAULT_PASSWORD: admin-tc
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - "5055:80"
    networks:
      - tickets
    restart: unless-stopped

networks:
  tickets:
    driver: bridge